# -*- coding: utf-8 -*-

# Run this app with `python app.py` and
# visit http://127.0.0.1:8050/ in your web browser.

import dash
import dash_daq as daq
from dash import dcc
from dash import html
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import matplotlib.pyplot as plt
import math
import re
import os
import numpy as np
from scipy import stats
pd.options.plotting.backend = "plotly"


# Directories
case_dir='beta_1'                                                                         # case directory
base_dir=os.getcwd()                                                                      # base directroy
# Beta=1.0 files
# b_1_vel='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_1/velocity/Uavg_1.00000E+1' 
# b_1_str='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_1/stress/Cavg_1.00000E+1'
# b_1_thy='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_1/plots/theory'
# Beta=0.8 files
os.chdir('/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_08/velocity')
df_b08_vel=pd.read_csv('Uavg_1.00000E+02', delim_whitespace=True, header=None, skiprows=1, usecols=[0,1], names=['Height','Uavg'])
os.chdir('/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_08/stress')
df_b08_str=pd.read_csv('Cavg_1.00000E+02', delim_whitespace=True, header=None, skiprows=1, usecols=[0,4,5], names=['Height','Txx_avg','Txy_avg'])
os.chdir('/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_08/plots')
df_b08_thy=pd.read_csv('theory', delim_whitespace=True, header=None, skiprows=1, usecols=[0,1,2,3], names=['Height','u','Txx','Txy'])
# b_08_vel='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_08/velocity/Uavg_1.00000E+1' 
# b_08_str='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_08/stress/Cavg_1.00000E+1'
# b_08_thy='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_08/plots/theory'
# Load Beta=0.8 files
# df_b08_vel=pd.read_csv(b_08_vel, delim_whitespace=True, header=None, skiprows=1, usecols=[0], names=['Height'])
# df_b08_vel=pd.read_csv(b_08_vel, delim_whitespace=True, header=None, skiprows=1, usecols=[0,1], names=['Height','Uavg'])
# df_b08_str=pd.read_csv(b_08_str, delim_whitespace=True, header=None, skiprows=1, usecols=[0,1], names=['Height','Uavg'])
# df_b08_thy=pd.read_csv(b_08_thy, delim_whitespace=True, header=None, skiprows=1, usecols=[0,4,5,6], names=['Height','u','Txx','Txy'])
# # Beta=0.6 files
# b_06_vel='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_06/velocity/Uavg_1.00000E+1' 
# b_06_str='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_06/stress/Cavg_1.00000E+1' 
# b_06_thy='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_06/plots/theory'
# # Beta=0.4 files
# b_04_vel='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_04/velocity/Uavg_1.00000E+1' 
# b_04_str='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_04/stress/Cavg_1.00000E+1'
# b_04_thy='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_06/plots/theory'
# # Beta=0.2 files
# b_02_vel='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_02/velocity/Uavg_1.00000E+1' 
# b_02_str='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_02/stress/Cavg_1.00000E+1'
# b_02_thy='/Users/josephgiliberto/Builds/NGA2/examples/channel/cases/beta_02/plots/theory'          

os.chdir(base_dir)

# Plot velocity/stress comparison along channel height
fig1=go.Figure()
fig1.add_trace(go.Scatter(mode='markers',x=df_b08_vel['Uavg'], y=df_b08_vel['Height'], showlegend=False))
fig1.add_trace(go.Scatter.line(mode='markers',x=df_b08_thy['u'], y=df_b08_thy['Height'], showlegend=False)) 
fig1.Line
fig1.update_layout(width=800,height=600)
# fig1.update_xaxes(type='log',title_text='$\Large{d/D}$',exponentformat="power",title_font_size=48,tickfont_size=24)
# fig1.update_yaxes(type='log',title_text='$\Large{\mathrm{{PDF}}(d)D}$', exponentformat="power",title_font_size=48,tickfont_size=24)

# This is where we define the dashboard layout
app = dash.Dash(__name__)
app.layout = html.Div(style={"margin-left": "15px"},children=[

    # Title of doc
    dcc.Markdown('''# Channnel flow of a Viscoelastic Fluid'''),
    dcc.Markdown('''*NGA2 Dashboard written by J. Giliberto, last updated 07/19/2023*'''),
    
    # Intro
    dcc.Markdown('''
    ## Overview

    In this dashboard, we post-process the raw data generated by NGA2's channel
    case.
    '''),
    
    # Simulation parameters
    dcc.Markdown(f'''
    ---
    ## Simulation parameters

    To be updated.

    ''',mathjax=True),
    
    # Droplet size distribution 
    # first row
    html.Div([
            dcc.Markdown(f'''
            ---
            ## Velocity profile
            
            The graph below shows the velocity profile of a viscoelastic fluid with different viscosity ratios.
            ''',mathjax=True),

    ],className='row'),

    
    # second row
    html.Div(
    [
        # first column
        html.Div(
            [
                dcc.Graph(id="drop_size", figure=fig1,mathjax=True)],
            style={"width": "65%", "float": "left", "display": "inline-block"},
        ),

    ],
    style={"margin": "40px"},className='row'
),
    
    
]) # End app




if __name__ == '__main__':
    app.run_server(debug=True)
